### ISSUE TITLE
Create BaseEntity class

### ISSUE THREAD

**Issue by Willjobs94** [Jherrera31/MovieStore#14]
# Que hacer?

1. Crear un folder dentro de la solucion llamado *Infrastructure*
2. Crear una clase que se llame *BaseEntity* dentro del folder *Infrastructure*
3. Agregar las siguentes propiedades a la clase *BaseEntity*, esta clase debe ser _abstract_

     * **Id** (del tipo *int*)
     * **CreatedAt** (del tipo *DateTime*)
     * **UpdatedAt** (del tipo *DateTime*)
     * **IsDeleted** (del tipo *bool*)
     * **DeletedAt** (del tipo *DateTime*)

**Comment by Willjobs94** [comment]
@JeffersonBenzan ya puedes cerrar este issue

**Comment by JeffersonBenzan** [comment]
Sorry, done!
